// `.env.json` is generated by the `npm run build` command
import env from './.env.json';

export const environment = {
  appName: 'LUNZ+',
  production: true,
  version: env.npm_package_version,
  localeId: 'zh-CN',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
