// `.env.json` is generated by the `npm run build` command
import env from './.env.json';

export const environment = {
  appName: 'LUNZ+',
  production: true,
  version: env.npm_package_version,
  localeId: 'zh-CN',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  // Web Api
  serverUrl: 'NOT-SET',
  appKey: 'NOT-SET',
  withHeaders: false,
  // User Center
  userCenter: {
    serverUrl: 'NOT-SET',
    appKey: 'NOT-SET',
    authUri: 'NOT-SET'
  },
  // Message Center
  msgCenter: {
    signalR: 'NOT-SET',
    serverUrl: 'NOT-SET',
    appKey: 'NOT-SET'
  }
};
